# input path
input_path: 'D:/test_images/original'

# output path
output_path: 'D:/test_images/center'

# output format
# choices=['jpg', 'png', 'jp2', 'tif']
output_format: 'jpg'

# mode
# choices=['center', 'grid']
mode: 'center'

# crop size
crop_size: [1024, 1024]

center:
  # specify center coordinates
  center: [1000, 1000]

grid:
  # gap size
  gap_size: 24

output_params:
  jpg:
    jpg_quality: 10
  jp2:
    jp2_compression: 950
  tif:
    swap_rb_channel: False
    # tif_data_type: None
